version: 2.1
jobs:
  unit-test-cases:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  android-ios:
    jobs:
      - unit-test-cases:
          filters:
            branches:
              only:
                - main
                - mushood/feature/snapshot-testing
