name: Build and Test

on:
  push:
    branches:
      - main
      - mushood/feature/snapshot-testing
  pull_request:
    branches:
      - main
      - mushood/feature/snapshot-testing

jobs:
  unit-test-cases:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
        
# name: Build and Test

# on:
#   push:
#     branches:
#       - main
#       - mushood/feature/snapshot-testing
#   pull_request:
#     branches:
#       - main
#       - mushood/feature/snapshot-testing

# jobs:
#   unit-test-cases:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         run: yarn install

#       - name: Run tests
#         run: yarn test

#   build-android:
#     needs: unit-test-cases
#     uses: ./.github/workflows/build-android.yml
#     secrets: inherit
