name: Build and Test

on:
  push:
    branches:
      - main
      - mushood/feature/snapshot-testing
  pull_request:
    branches:
      - main
      - mushood/feature/snapshot-testing

jobs:
   unit-test-cases:
    # Install node dependencies and run tests
    executor: node/default
    runs-on: self-hosted
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
